/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: meta.proto */

#ifndef PROTOBUF_C_meta_2eproto__INCLUDED
#define PROTOBUF_C_meta_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Package Package;


/* --- enums --- */


/* --- messages --- */

struct  _Package
{
  ProtobufCMessage base;
  char *virtualpath;
  char *realfullpath;
  protobuf_c_boolean has_isdir;
  protobuf_c_boolean isdir;
  protobuf_c_boolean has_replicanum;
  int32_t replicanum;
  size_t n_listitem;
  char **listitem;
};
#define PACKAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&package__descriptor) \
    , NULL, NULL, 0,0, 0,0, 0,NULL }


/* Package methods */
void   package__init
                     (Package         *message);
size_t package__get_packed_size
                     (const Package   *message);
size_t package__pack
                     (const Package   *message,
                      uint8_t             *out);
size_t package__pack_to_buffer
                     (const Package   *message,
                      ProtobufCBuffer     *buffer);
Package *
       package__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   package__free_unpacked
                     (Package *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Package_Closure)
                 (const Package *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor package__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_meta_2eproto__INCLUDED */
