/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: metamatrix.proto */

#ifndef PROTOBUF_C_metamatrix_2eproto__INCLUDED
#define PROTOBUF_C_metamatrix_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MatrixMsg MatrixMsg;


/* --- enums --- */


/* --- messages --- */

struct  _MatrixMsg
{
  ProtobufCMessage base;
  char *msgtype;
  char *extrainfo;
  protobuf_c_boolean has_count;
  int64_t count;
  size_t n_tasks;
  char **tasks;
};
#define MATRIX_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&matrix_msg__descriptor) \
    , NULL, NULL, 0,0, 0,NULL }


/* MatrixMsg methods */
void   matrix_msg__init
                     (MatrixMsg         *message);
size_t matrix_msg__get_packed_size
                     (const MatrixMsg   *message);
size_t matrix_msg__pack
                     (const MatrixMsg   *message,
                      uint8_t             *out);
size_t matrix_msg__pack_to_buffer
                     (const MatrixMsg   *message,
                      ProtobufCBuffer     *buffer);
MatrixMsg *
       matrix_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   matrix_msg__free_unpacked
                     (MatrixMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MatrixMsg_Closure)
                 (const MatrixMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor matrix_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_metamatrix_2eproto__INCLUDED */
