/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: metamatrix.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "metamatrix.pb-c.h"
void   matrix_msg__init
                     (MatrixMsg         *message)
{
  static MatrixMsg init_value = MATRIX_MSG__INIT;
  *message = init_value;
}
size_t matrix_msg__get_packed_size
                     (const MatrixMsg *message)
{
  assert(message->base.descriptor == &matrix_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t matrix_msg__pack
                     (const MatrixMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &matrix_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t matrix_msg__pack_to_buffer
                     (const MatrixMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &matrix_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MatrixMsg *
       matrix_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MatrixMsg *)
     protobuf_c_message_unpack (&matrix_msg__descriptor,
                                allocator, len, data);
}
void   matrix_msg__free_unpacked
                     (MatrixMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &matrix_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor matrix_msg__field_descriptors[4] =
{
  {
    "msgType",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MatrixMsg, msgtype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extraInfo",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(MatrixMsg, extrainfo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(MatrixMsg, has_count),
    offsetof(MatrixMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tasks",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(MatrixMsg, n_tasks),
    offsetof(MatrixMsg, tasks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned matrix_msg__field_indices_by_name[] = {
  2,   /* field[2] = count */
  1,   /* field[1] = extraInfo */
  0,   /* field[0] = msgType */
  3,   /* field[3] = tasks */
};
static const ProtobufCIntRange matrix_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor matrix_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MatrixMsg",
  "MatrixMsg",
  "MatrixMsg",
  "",
  sizeof(MatrixMsg),
  4,
  matrix_msg__field_descriptors,
  matrix_msg__field_indices_by_name,
  1,  matrix_msg__number_ranges,
  (ProtobufCMessageInit) matrix_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
