// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metamatrix.proto

#ifndef PROTOBUF_metamatrix_2eproto__INCLUDED
#define PROTOBUF_metamatrix_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_metamatrix_2eproto();
void protobuf_AssignDesc_metamatrix_2eproto();
void protobuf_ShutdownFile_metamatrix_2eproto();

class MatrixMsg;

// ===================================================================

class MatrixMsg : public ::google::protobuf::Message {
 public:
  MatrixMsg();
  virtual ~MatrixMsg();
  
  MatrixMsg(const MatrixMsg& from);
  
  inline MatrixMsg& operator=(const MatrixMsg& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MatrixMsg& default_instance();
  
  void Swap(MatrixMsg* other);
  
  // implements Message ----------------------------------------------
  
  MatrixMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MatrixMsg& from);
  void MergeFrom(const MatrixMsg& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string msgType = 1;
  inline bool has_msgtype() const;
  inline void clear_msgtype();
  static const int kMsgTypeFieldNumber = 1;
  inline const ::std::string& msgtype() const;
  inline void set_msgtype(const ::std::string& value);
  inline void set_msgtype(const char* value);
  inline void set_msgtype(const char* value, size_t size);
  inline ::std::string* mutable_msgtype();
  inline ::std::string* release_msgtype();
  
  // optional string extraInfo = 2;
  inline bool has_extrainfo() const;
  inline void clear_extrainfo();
  static const int kExtraInfoFieldNumber = 2;
  inline const ::std::string& extrainfo() const;
  inline void set_extrainfo(const ::std::string& value);
  inline void set_extrainfo(const char* value);
  inline void set_extrainfo(const char* value, size_t size);
  inline ::std::string* mutable_extrainfo();
  inline ::std::string* release_extrainfo();
  
  // optional int64 count = 3;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 3;
  inline ::google::protobuf::int64 count() const;
  inline void set_count(::google::protobuf::int64 value);
  
  // repeated string tasks = 4;
  inline int tasks_size() const;
  inline void clear_tasks();
  static const int kTasksFieldNumber = 4;
  inline const ::std::string& tasks(int index) const;
  inline ::std::string* mutable_tasks(int index);
  inline void set_tasks(int index, const ::std::string& value);
  inline void set_tasks(int index, const char* value);
  inline void set_tasks(int index, const char* value, size_t size);
  inline ::std::string* add_tasks();
  inline void add_tasks(const ::std::string& value);
  inline void add_tasks(const char* value);
  inline void add_tasks(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& tasks() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_tasks();
  
  // @@protoc_insertion_point(class_scope:MatrixMsg)
 private:
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_extrainfo();
  inline void clear_has_extrainfo();
  inline void set_has_count();
  inline void clear_has_count();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* msgtype_;
  ::std::string* extrainfo_;
  ::google::protobuf::int64 count_;
  ::google::protobuf::RepeatedPtrField< ::std::string> tasks_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_metamatrix_2eproto();
  friend void protobuf_AssignDesc_metamatrix_2eproto();
  friend void protobuf_ShutdownFile_metamatrix_2eproto();
  
  void InitAsDefaultInstance();
  static MatrixMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// MatrixMsg

// required string msgType = 1;
inline bool MatrixMsg::has_msgtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MatrixMsg::set_has_msgtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MatrixMsg::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MatrixMsg::clear_msgtype() {
  if (msgtype_ != &::google::protobuf::internal::kEmptyString) {
    msgtype_->clear();
  }
  clear_has_msgtype();
}
inline const ::std::string& MatrixMsg::msgtype() const {
  return *msgtype_;
}
inline void MatrixMsg::set_msgtype(const ::std::string& value) {
  set_has_msgtype();
  if (msgtype_ == &::google::protobuf::internal::kEmptyString) {
    msgtype_ = new ::std::string;
  }
  msgtype_->assign(value);
}
inline void MatrixMsg::set_msgtype(const char* value) {
  set_has_msgtype();
  if (msgtype_ == &::google::protobuf::internal::kEmptyString) {
    msgtype_ = new ::std::string;
  }
  msgtype_->assign(value);
}
inline void MatrixMsg::set_msgtype(const char* value, size_t size) {
  set_has_msgtype();
  if (msgtype_ == &::google::protobuf::internal::kEmptyString) {
    msgtype_ = new ::std::string;
  }
  msgtype_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MatrixMsg::mutable_msgtype() {
  set_has_msgtype();
  if (msgtype_ == &::google::protobuf::internal::kEmptyString) {
    msgtype_ = new ::std::string;
  }
  return msgtype_;
}
inline ::std::string* MatrixMsg::release_msgtype() {
  clear_has_msgtype();
  if (msgtype_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = msgtype_;
    msgtype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string extraInfo = 2;
inline bool MatrixMsg::has_extrainfo() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MatrixMsg::set_has_extrainfo() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MatrixMsg::clear_has_extrainfo() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MatrixMsg::clear_extrainfo() {
  if (extrainfo_ != &::google::protobuf::internal::kEmptyString) {
    extrainfo_->clear();
  }
  clear_has_extrainfo();
}
inline const ::std::string& MatrixMsg::extrainfo() const {
  return *extrainfo_;
}
inline void MatrixMsg::set_extrainfo(const ::std::string& value) {
  set_has_extrainfo();
  if (extrainfo_ == &::google::protobuf::internal::kEmptyString) {
    extrainfo_ = new ::std::string;
  }
  extrainfo_->assign(value);
}
inline void MatrixMsg::set_extrainfo(const char* value) {
  set_has_extrainfo();
  if (extrainfo_ == &::google::protobuf::internal::kEmptyString) {
    extrainfo_ = new ::std::string;
  }
  extrainfo_->assign(value);
}
inline void MatrixMsg::set_extrainfo(const char* value, size_t size) {
  set_has_extrainfo();
  if (extrainfo_ == &::google::protobuf::internal::kEmptyString) {
    extrainfo_ = new ::std::string;
  }
  extrainfo_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MatrixMsg::mutable_extrainfo() {
  set_has_extrainfo();
  if (extrainfo_ == &::google::protobuf::internal::kEmptyString) {
    extrainfo_ = new ::std::string;
  }
  return extrainfo_;
}
inline ::std::string* MatrixMsg::release_extrainfo() {
  clear_has_extrainfo();
  if (extrainfo_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = extrainfo_;
    extrainfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int64 count = 3;
inline bool MatrixMsg::has_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MatrixMsg::set_has_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MatrixMsg::clear_has_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MatrixMsg::clear_count() {
  count_ = GOOGLE_LONGLONG(0);
  clear_has_count();
}
inline ::google::protobuf::int64 MatrixMsg::count() const {
  return count_;
}
inline void MatrixMsg::set_count(::google::protobuf::int64 value) {
  set_has_count();
  count_ = value;
}

// repeated string tasks = 4;
inline int MatrixMsg::tasks_size() const {
  return tasks_.size();
}
inline void MatrixMsg::clear_tasks() {
  tasks_.Clear();
}
inline const ::std::string& MatrixMsg::tasks(int index) const {
  return tasks_.Get(index);
}
inline ::std::string* MatrixMsg::mutable_tasks(int index) {
  return tasks_.Mutable(index);
}
inline void MatrixMsg::set_tasks(int index, const ::std::string& value) {
  tasks_.Mutable(index)->assign(value);
}
inline void MatrixMsg::set_tasks(int index, const char* value) {
  tasks_.Mutable(index)->assign(value);
}
inline void MatrixMsg::set_tasks(int index, const char* value, size_t size) {
  tasks_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MatrixMsg::add_tasks() {
  return tasks_.Add();
}
inline void MatrixMsg::add_tasks(const ::std::string& value) {
  tasks_.Add()->assign(value);
}
inline void MatrixMsg::add_tasks(const char* value) {
  tasks_.Add()->assign(value);
}
inline void MatrixMsg::add_tasks(const char* value, size_t size) {
  tasks_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MatrixMsg::tasks() const {
  return tasks_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MatrixMsg::mutable_tasks() {
  return &tasks_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_metamatrix_2eproto__INCLUDED
