/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: metatask.proto */

#ifndef PROTOBUF_C_metatask_2eproto__INCLUDED
#define PROTOBUF_C_metatask_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _TaskMsg TaskMsg;


/* --- enums --- */


/* --- messages --- */

struct  _TaskMsg
{
  ProtobufCMessage base;
  char *taskid;
  char *user;
  char *dir;
  char *cmd;
  int64_t datalength;
};
#define TASK_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&task_msg__descriptor) \
    , NULL, NULL, NULL, NULL, 0 }


/* TaskMsg methods */
void   task_msg__init
                     (TaskMsg         *message);
size_t task_msg__get_packed_size
                     (const TaskMsg   *message);
size_t task_msg__pack
                     (const TaskMsg   *message,
                      uint8_t             *out);
size_t task_msg__pack_to_buffer
                     (const TaskMsg   *message,
                      ProtobufCBuffer     *buffer);
TaskMsg *
       task_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   task_msg__free_unpacked
                     (TaskMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TaskMsg_Closure)
                 (const TaskMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor task_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_metatask_2eproto__INCLUDED */
