/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: metatask.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "metatask.pb-c.h"
void   task_msg__init
                     (TaskMsg         *message)
{
  static TaskMsg init_value = TASK_MSG__INIT;
  *message = init_value;
}
size_t task_msg__get_packed_size
                     (const TaskMsg *message)
{
  assert(message->base.descriptor == &task_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t task_msg__pack
                     (const TaskMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &task_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t task_msg__pack_to_buffer
                     (const TaskMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &task_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TaskMsg *
       task_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TaskMsg *)
     protobuf_c_message_unpack (&task_msg__descriptor,
                                allocator, len, data);
}
void   task_msg__free_unpacked
                     (TaskMsg *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &task_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor task_msg__field_descriptors[5] =
{
  {
    "taskId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TaskMsg, taskid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TaskMsg, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dir",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TaskMsg, dir),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TaskMsg, cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataLength",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(TaskMsg, datalength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned task_msg__field_indices_by_name[] = {
  3,   /* field[3] = cmd */
  4,   /* field[4] = dataLength */
  2,   /* field[2] = dir */
  0,   /* field[0] = taskId */
  1,   /* field[1] = user */
};
static const ProtobufCIntRange task_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor task_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TaskMsg",
  "TaskMsg",
  "TaskMsg",
  "",
  sizeof(TaskMsg),
  5,
  task_msg__field_descriptors,
  task_msg__field_indices_by_name,
  1,  task_msg__number_ranges,
  (ProtobufCMessageInit) task_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
