// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "metamatrix.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MatrixMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MatrixMsg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_metamatrix_2eproto() {
  protobuf_AddDesc_metamatrix_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "metamatrix.proto");
  GOOGLE_CHECK(file != NULL);
  MatrixMsg_descriptor_ = file->message_type(0);
  static const int MatrixMsg_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatrixMsg, msgtype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatrixMsg, extrainfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatrixMsg, count_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatrixMsg, tasks_),
  };
  MatrixMsg_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MatrixMsg_descriptor_,
      MatrixMsg::default_instance_,
      MatrixMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatrixMsg, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MatrixMsg, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MatrixMsg));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_metamatrix_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MatrixMsg_descriptor_, &MatrixMsg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_metamatrix_2eproto() {
  delete MatrixMsg::default_instance_;
  delete MatrixMsg_reflection_;
}

void protobuf_AddDesc_metamatrix_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020metamatrix.proto\"M\n\tMatrixMsg\022\017\n\007msgTy"
    "pe\030\001 \002(\t\022\021\n\textraInfo\030\002 \001(\t\022\r\n\005count\030\003 \001"
    "(\003\022\r\n\005tasks\030\004 \003(\t", 97);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "metamatrix.proto", &protobuf_RegisterTypes);
  MatrixMsg::default_instance_ = new MatrixMsg();
  MatrixMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_metamatrix_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_metamatrix_2eproto {
  StaticDescriptorInitializer_metamatrix_2eproto() {
    protobuf_AddDesc_metamatrix_2eproto();
  }
} static_descriptor_initializer_metamatrix_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int MatrixMsg::kMsgTypeFieldNumber;
const int MatrixMsg::kExtraInfoFieldNumber;
const int MatrixMsg::kCountFieldNumber;
const int MatrixMsg::kTasksFieldNumber;
#endif  // !_MSC_VER

MatrixMsg::MatrixMsg()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MatrixMsg::InitAsDefaultInstance() {
}

MatrixMsg::MatrixMsg(const MatrixMsg& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MatrixMsg::SharedCtor() {
  _cached_size_ = 0;
  msgtype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  extrainfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  count_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MatrixMsg::~MatrixMsg() {
  SharedDtor();
}

void MatrixMsg::SharedDtor() {
  if (msgtype_ != &::google::protobuf::internal::kEmptyString) {
    delete msgtype_;
  }
  if (extrainfo_ != &::google::protobuf::internal::kEmptyString) {
    delete extrainfo_;
  }
  if (this != default_instance_) {
  }
}

void MatrixMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MatrixMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MatrixMsg_descriptor_;
}

const MatrixMsg& MatrixMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_metamatrix_2eproto();  return *default_instance_;
}

MatrixMsg* MatrixMsg::default_instance_ = NULL;

MatrixMsg* MatrixMsg::New() const {
  return new MatrixMsg;
}

void MatrixMsg::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_msgtype()) {
      if (msgtype_ != &::google::protobuf::internal::kEmptyString) {
        msgtype_->clear();
      }
    }
    if (has_extrainfo()) {
      if (extrainfo_ != &::google::protobuf::internal::kEmptyString) {
        extrainfo_->clear();
      }
    }
    count_ = GOOGLE_LONGLONG(0);
  }
  tasks_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MatrixMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string msgType = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msgtype()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->msgtype().data(), this->msgtype().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_extraInfo;
        break;
      }
      
      // optional string extraInfo = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_extraInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_extrainfo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->extrainfo().data(), this->extrainfo().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_count;
        break;
      }
      
      // optional int64 count = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &count_)));
          set_has_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_tasks;
        break;
      }
      
      // repeated string tasks = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_tasks:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_tasks()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->tasks(0).data(), this->tasks(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_tasks;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MatrixMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string msgType = 1;
  if (has_msgtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msgtype().data(), this->msgtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->msgtype(), output);
  }
  
  // optional string extraInfo = 2;
  if (has_extrainfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->extrainfo().data(), this->extrainfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->extrainfo(), output);
  }
  
  // optional int64 count = 3;
  if (has_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->count(), output);
  }
  
  // repeated string tasks = 4;
  for (int i = 0; i < this->tasks_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->tasks(i).data(), this->tasks(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->tasks(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MatrixMsg::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string msgType = 1;
  if (has_msgtype()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->msgtype().data(), this->msgtype().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msgtype(), target);
  }
  
  // optional string extraInfo = 2;
  if (has_extrainfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->extrainfo().data(), this->extrainfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->extrainfo(), target);
  }
  
  // optional int64 count = 3;
  if (has_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->count(), target);
  }
  
  // repeated string tasks = 4;
  for (int i = 0; i < this->tasks_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->tasks(i).data(), this->tasks(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->tasks(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MatrixMsg::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string msgType = 1;
    if (has_msgtype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msgtype());
    }
    
    // optional string extraInfo = 2;
    if (has_extrainfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->extrainfo());
    }
    
    // optional int64 count = 3;
    if (has_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->count());
    }
    
  }
  // repeated string tasks = 4;
  total_size += 1 * this->tasks_size();
  for (int i = 0; i < this->tasks_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->tasks(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MatrixMsg::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MatrixMsg* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MatrixMsg*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MatrixMsg::MergeFrom(const MatrixMsg& from) {
  GOOGLE_CHECK_NE(&from, this);
  tasks_.MergeFrom(from.tasks_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_msgtype()) {
      set_msgtype(from.msgtype());
    }
    if (from.has_extrainfo()) {
      set_extrainfo(from.extrainfo());
    }
    if (from.has_count()) {
      set_count(from.count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MatrixMsg::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MatrixMsg::CopyFrom(const MatrixMsg& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatrixMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void MatrixMsg::Swap(MatrixMsg* other) {
  if (other != this) {
    std::swap(msgtype_, other->msgtype_);
    std::swap(extrainfo_, other->extrainfo_);
    std::swap(count_, other->count_);
    tasks_.Swap(&other->tasks_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MatrixMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MatrixMsg_descriptor_;
  metadata.reflection = MatrixMsg_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
